/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sdklibrary_SDK */

#ifndef _Included_com_example_sdklibrary_SDK
#define _Included_com_example_sdklibrary_SDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sdklibrary_SDK
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sdklibrary_SDK_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_sdklibrary_SDK
 * Method:    getAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_sdklibrary_SDK_getAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
